### ISSUE TITLE
Deleting documents assigned to annotation task without deleting annotation task

### ISSUE THREAD

**Issue by brandontoups** [IBM-Bluemix-Docs/watson-knowledge-studio#77]
Hi,

I am having trouble with bad data sets. I was wondering why annotation tasks lock documents in. What I mean is that documents can not be deleted if they are associated with an annotation task. However, if I have already started an annotation task, then deleting the annotation task in order to delete that document from the document set would render my previous work on that annotation set useless. 

I can see the POV of trash in -> trash out wrt training, and it would be beneficial to modify and changes and delete any bad .txt datasets BEFORE I even upload these files into WKS. The problem is, however, that I often fail to realize my bad data files are bad until I am halfway through an annotation task. This is because WKS mention/relation/coreference editor is actually fantastic -- far more intuitive than my text editor, so I find errors much quicker. 

Summary: is there a reason document sets cannot be removed directly from annotation sets? I don't want to remove the annotation task that I have already started, but I don't want the bad data lessening the accuracy of training and evaluation. 

Just wanted to know what y'all thought about that.

**Comment by jdicarl** [comment]
Hi Brandon. Thanks for using Watson Knowledge Studio! I'm sorry to hear that you're having trouble with removing document sets. I'll do my best to help, but keep in mind that this repo is for the documentation, not product [support](https://cloud.ibm.com/docs/services/watson-knowledge-studio?topic=watson-knowledge-studio-troubleshooting#ts_contactingibmsupport).

- If I understand you correctly, you know how to remove documents already. If not, have a look at the section in the documentation about deleting documents: https://cloud.ibm.com/docs/services/watson-knowledge-studio?topic=watson-knowledge-studio-documents-for-annotation#wks_deletedocs
- If your question is more, _Why does Knowledge Studio work this way?_ Unfortunately, I can't give you a definitive answer because I'm not a product owner who has made decisions about how and why Knowledge Studio works the way that it does. But your point might be interesting for the product owners to hear. If you're interested in adding an idea to the [IBM Watson Ideas Portal](https://ibm-watson.ideas.aha.io/?project=WKS), here's the URL: https://ibm-watson.ideas.aha.io/?project=WKS.
- If you're just curious what the benefit is of having Knowledge Studio work this way, maybe you can ask your question in one of the following developer communities and get some feedback there. I'd recommend searching first to see if your question was already asked and answered:
  * https://stackoverflow.com/search?q=watson-knowledge-studio
  * https://developer.ibm.com/answers/topics/watson-knowledge-studio/
  * http://wdc-slack-inviter.mybluemix.net/

  **Note**: Links to those communities are available in the HELP section of the documentation, right below the [troubleshooting section for the ground truth editor](https://cloud.ibm.com/docs/services/watson-knowledge-studio?topic=watson-knowledge-studio-ts_user_contactingsupport), as shown in the following screencap.
![image](https://user-images.githubusercontent.com/13224537/54639859-c1326080-4a64-11e9-9b04-cf1ccf04fde9.png)

**Comment by brandontoups** [comment]
Oh I see. I didn't even catch that this was just for the docs. I will take a look at those links and pose the question in another place. 

For context, this was more so a "Why does WKS work this way". Feel free to close this issue, as my initial issue is not really appropriate for this repo. 

Thanks for your help on this, and I appreciate you taking the time to respond with so much information.
